---
abstract: 'parse Search::OpenSearch::Response::XML '
author:
  - 'Peter Karman <karman@cpan.org>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.140640'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Search-OpenSearch-FeedParser
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dump: '0'
  Data::Transformer: '0'
  Moo: '0'
  Search::Tools: '1.000'
  Test::More: '0'
  Type::Tiny: '0'
  XML::Feed: '0'
  XML::Simple: '0'
version: '0.100'
